// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using NexusFlow.Integrations.Infrastructure;

#nullable disable

namespace NexusFlow.Integrations.Infrastructure.Migrations;

[DbContext(typeof(IntegrationsDbContext))]
partial class IntegrationsDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("NexusFlow.Integrations.Domain.UserIntegration", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("CredentialsEncrypted").IsRequired().HasColumnType("text");
            b.Property<string>("Label").IsRequired().HasMaxLength(80).HasColumnType("character varying(80)");
            b.Property<DateTimeOffset?>("LastUsedAt").HasColumnType("timestamp with time zone");
            b.Property<int>("Provider").HasColumnType("integer");
            b.Property<DateTimeOffset?>("RevokedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.Property<Guid>("UserId").HasColumnType("uuid");

            b.HasKey("Id");
            b.HasIndex("UserId", "Provider");
            b.HasIndex("UserId", "RevokedAt");
            b.ToTable("int_user_integrations", (string)null);
        });
#pragma warning restore 612, 618
    }
}
