// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NexusFlow.Executions.Infrastructure;

#nullable disable

namespace NexusFlow.Executions.Infrastructure.Migrations;

[DbContext(typeof(ExecutionsDbContext))]
[Migration("20260516000003_InitialExecutions")]
partial class InitialExecutions
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("NexusFlow.Executions.Domain.Execution", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<int?>("DurationMs").HasColumnType("integer");
            b.Property<string>("ErrorMessage").HasMaxLength(2000).HasColumnType("character varying(2000)");
            b.Property<DateTimeOffset?>("FinishedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset?>("StartedAt").HasColumnType("timestamp with time zone");
            b.Property<int>("Status").HasColumnType("integer");
            b.Property<int>("TriggeredBy").HasColumnType("integer");
            b.Property<string>("TriggerPayload").IsRequired().HasColumnType("jsonb");
            b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.Property<Guid>("WorkflowId").HasColumnType("uuid");

            b.HasKey("Id");
            b.HasIndex("UserId", "CreatedAt");
            b.HasIndex("WorkflowId", "Status");
            b.HasIndex("WorkflowId", "CreatedAt");
            b.ToTable("exec_executions", (string)null);
        });

        modelBuilder.Entity("NexusFlow.Executions.Domain.StepExecution", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<string>("ActionType").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<int?>("DurationMs").HasColumnType("integer");
            b.Property<string>("Error").HasMaxLength(4000).HasColumnType("character varying(4000)");
            b.Property<Guid>("ExecutionId").HasColumnType("uuid");
            b.Property<DateTimeOffset?>("FinishedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("Input").IsRequired().HasColumnType("jsonb");
            b.Property<int>("OrderIndex").HasColumnType("integer");
            b.Property<string>("Output").IsRequired().HasColumnType("jsonb");
            b.Property<DateTimeOffset?>("StartedAt").HasColumnType("timestamp with time zone");
            b.Property<int>("Status").HasColumnType("integer");
            b.Property<Guid>("StepId").HasColumnType("uuid");
            b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("timestamp with time zone");

            b.HasKey("Id");
            b.HasIndex("ExecutionId", "OrderIndex");
            b.ToTable("exec_step_executions", (string)null);
        });

        modelBuilder.Entity("NexusFlow.Executions.Domain.WorkflowOutput", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<Guid>("ExecutionId").HasColumnType("uuid");
            b.Property<string>("Payload").IsRequired().HasColumnType("jsonb");
            b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.Property<Guid>("WorkflowId").HasColumnType("uuid");

            b.HasKey("Id");
            b.HasIndex("ExecutionId");
            b.HasIndex("WorkflowId", "CreatedAt");
            b.ToTable("exec_workflow_outputs", (string)null);
        });

        modelBuilder.Entity("NexusFlow.Executions.Domain.StepExecution", b =>
        {
            b.HasOne("NexusFlow.Executions.Domain.Execution", null)
                .WithMany("Steps")
                .HasForeignKey("ExecutionId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("NexusFlow.Executions.Domain.Execution", b =>
        {
            b.Navigation("Steps");
        });
#pragma warning restore 612, 618
    }
}
