// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using NexusFlow.Workflows.Infrastructure;

#nullable disable

namespace NexusFlow.Workflows.Infrastructure.Migrations;

[DbContext(typeof(WorkflowsDbContext))]
[Migration("20260520000005_AddWorkflowLayout")]
partial class AddWorkflowLayout
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("NexusFlow.Workflows.Domain.Workflow", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("Description").HasMaxLength(2000).HasColumnType("character varying(2000)");
            b.Property<bool>("IsActive").HasColumnType("boolean");
            b.Property<string>("Layout").HasColumnType("jsonb");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<string>("TriggerConfig").IsRequired().HasColumnType("jsonb");
            b.Property<int>("TriggerType").HasColumnType("integer");
            b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.Property<Guid>("UserId").HasColumnType("uuid");

            b.HasKey("Id");
            b.HasIndex("UserId", "IsActive");
            b.HasIndex("UserId", "CreatedAt");
            b.ToTable("wf_workflows", (string)null);
        });

        modelBuilder.Entity("NexusFlow.Workflows.Domain.WorkflowStep", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<int>("ActionType").HasColumnType("integer");
            b.Property<string>("Config").IsRequired().HasColumnType("jsonb");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<int>("OrderIndex").HasColumnType("integer");
            b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.Property<Guid>("WorkflowId").HasColumnType("uuid");

            b.HasKey("Id");
            b.HasIndex("WorkflowId", "OrderIndex").IsUnique();
            b.ToTable("wf_steps", (string)null);
        });

        modelBuilder.Entity("NexusFlow.Workflows.Domain.WorkflowStep", b =>
        {
            b.HasOne("NexusFlow.Workflows.Domain.Workflow", null)
                .WithMany("Steps")
                .HasForeignKey("WorkflowId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("NexusFlow.Workflows.Domain.Workflow", b =>
        {
            b.Navigation("Steps");
        });
#pragma warning restore 612, 618
    }
}
