// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusFlow.Auth.Infrastructure;

#nullable disable

namespace NexusFlow.Auth.Infrastructure.Migrations;

[DbContext(typeof(AuthDbContext))]
[Migration("20260516000001_InitialAuth")]
partial class InitialAuth
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("NexusFlow.Auth.Domain.User", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<string>("PasswordHash").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
            b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("timestamp with time zone");

            b.HasKey("Id");
            b.HasIndex("Email").IsUnique();
            b.ToTable("auth_users", (string)null);
        });

        modelBuilder.Entity("NexusFlow.Auth.Domain.RefreshToken", b =>
        {
            b.Property<Guid>("Id").HasColumnType("uuid");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
            b.Property<DateTimeOffset>("ExpiresAt").HasColumnType("timestamp with time zone");
            b.Property<Guid?>("ReplacedByTokenId").HasColumnType("uuid");
            b.Property<DateTimeOffset?>("RevokedAt").HasColumnType("timestamp with time zone");
            b.Property<string>("TokenHash").IsRequired().HasMaxLength(512).HasColumnType("character varying(512)");
            b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("timestamp with time zone");
            b.Property<Guid>("UserId").HasColumnType("uuid");

            b.HasKey("Id");
            b.HasIndex("TokenHash").IsUnique();
            b.HasIndex("UserId", "RevokedAt");
            b.ToTable("auth_refresh_tokens", (string)null);
        });

        modelBuilder.Entity("NexusFlow.Auth.Domain.RefreshToken", b =>
        {
            b.HasOne("NexusFlow.Auth.Domain.User", null)
                .WithMany("RefreshTokens")
                .HasForeignKey("UserId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        modelBuilder.Entity("NexusFlow.Auth.Domain.User", b =>
        {
            b.Navigation("RefreshTokens");
        });
#pragma warning restore 612, 618
    }
}
